### ISSUE TITLE
Change Default Port Number with Command Line Argument

### ISSUE THREAD

**Issue by angelplusultra** [mmiscool/aiCoder#3]
## The Problem: 

Currently, there is no way to change the port number of the server. It is fixed at `5000`. 

## Potential Solution: 

Consume the port the number via an an optional command line argument provided by the developer. If no port number argument is provided the default port number will be used.

Example implementation:

```bash
aicoder -p 3000
```

### Option 1. Using a command line argument parsing library.

Might be a good investment to pull something off the shelf like [Commander](https://www.npmjs.com/package/commander) or [Yargs](https://www.npmjs.com/package/yargs)  in case the command line interface grows from here and gets more complex.

### Option 2. Using no libraries and just parse `process.argv`

No extra dependencies just yoink the argument from `argv` and we're off.

**Comment by mmiscool** [comment]
Added option to launch with a custom port number. 

Also changed default port to 3000
